version: '3.7'

services:
  helloapi:
    build:
      context: .
      dockerfile: Dockerfile
      target: helloapi_dev
    image: "helloapi"
    ports:
      - 8080:80
    volumes:
      - .:/helloapi
