version: '3.7'

services:
  helloapi:
    build:
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
      context: .
      dockerfile: Dockerfile
      target: helloapi_dev
    image: "helloapi"
    ports:
      - 8080:80
    volumes:
      - .:/helloapi
