apiVersion: v1
kind: Service
metadata:
  name: helloapi-svc
  namespace: helloapi
spec:
  selector:
    name: helloapi-pod
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31080
